# Generated by Django 2.2.16 on 2022-08-21 16:32

import csv
import os
from datetime import datetime

from django.db import migrations
from django.utils import timezone

from api_yamdb.settings import BASE_DIR

print(f'BASE_DIR: {BASE_DIR}')

def user_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    with open(
        os.path.join(BASE_DIR, 'static/data/users.csv'),
        encoding='utf-8'
    ) as file:
        reader = csv.reader(file)
        header = next(reader)
        users = []
        for row in reader:
            id = row[0]
            comment = next((b for b in users if b.id == id), None)
            if not comment:
                user = User(
                    id=row[0],
                    username=row[1],
                    email=row[2],
                    role=row[3],
                    password='testpassuser',
                    is_superuser=False,
                    is_staff=False,
                    is_active=True,
                    date_joined=datetime.now(tz=timezone.utc),
                    confirmation_code='testcode'
                )
                users.append(user)
    User.objects.bulk_create(users)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(user_data)
    ]
