# Generated by Django 2.2.16 on 2022-08-21 16:37

import csv
import os

from django.db import migrations

from api_yamdb.settings import BASE_DIR


def titles_data(apps, schema_editor):
    Category = apps.get_model('titles', 'Category')
    Genre = apps.get_model('titles', 'Genre')
    Title = apps.get_model('titles', 'Title')

    with open(
        os.path.join(BASE_DIR, 'static/data/category.csv'),
        encoding='utf-8'
    ) as file:
        reader = csv.reader(file)
        header = next(reader)
        categories = []
        for row in reader:
            id = row[0]
            category = next((b for b in categories if b.id == id), None)
            if not category:
                category = Category(
                    id=row[0],
                    name=row[1],
                    slug=row[2],
                )
                categories.append(category)
    Category.objects.bulk_create(categories)

    with open(
        os.path.join(BASE_DIR, 'static/data/genre.csv'),
        encoding='utf-8'
    ) as file:
        reader = csv.reader(file)
        header = next(reader)
        genres = []
        for row in reader:
            id = row[0]
            genre = next((b for b in genres if b.id == id), None)
            if not genre:
                genre = Genre(
                    id=row[0],
                    name=row[1],
                    slug=row[2],
                )
                genres.append(genre)
    Genre.objects.bulk_create(genres)

    with open(
        os.path.join(BASE_DIR, 'static/data/titles.csv'),
        encoding='utf-8'
    ) as file:
        reader = csv.reader(file)
        header = next(reader)
        titles = []
        for row in reader:
            id = row[0]
            title = next((b for b in titles if b.id == id), None)
            if not title:
                title = Title(
                    id=row[0],
                    name=row[1],
                    year=row[2],
                    category=Category(pk=row[3])
                )
                titles.append(title)
    Title.objects.bulk_create(titles)

    with open(
        os.path.join(BASE_DIR, 'static/data/genre_title.csv'),
        encoding='utf-8'
    ) as file:
        reader = csv.reader(file)
        header = next(reader)
        genres_titles = []
        for row in reader:
            id = row[0]
            header_skip = next((b for b in genres_titles if b.id == id), None)
            to = Title.objects.get(id=row[1])
            to.genre.add(row[2])


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(titles_data)
    ]
