# Generated by Django 2.2.16 on 2022-08-21 16:48

import csv
import os

from django.db import migrations

from api_yamdb.settings import BASE_DIR


def reviews_data(apps, schema_editor):
    Comment = apps.get_model('reviews', 'Comment')
    User = apps.get_model('users', 'User')
    Review = apps.get_model('reviews', 'Review')
    Title = apps.get_model('titles', 'Title')

    with open(
        os.path.join(BASE_DIR, 'static/data/review.csv'),
        encoding='utf-8'
    ) as file:
        reader = csv.reader(file)
        header = next(reader)
        reviews = []
        for row in reader:
            id = row[0]
            review = next((b for b in reviews if b.id == id), None)
            if not review:
                review = Review(
                    id=row[0],
                    title=Title.objects.get(id=row[1]),
                    text=row[2],
                    author=User.objects.get(id=row[3]),
                    score=row[4],
                    pub_date=row[5]
                )
                reviews.append(review)
    Review.objects.bulk_create(reviews)

    with open(
        os.path.join(BASE_DIR, 'static/data/comments.csv'),
        encoding='utf-8'
    ) as file:
        reader = csv.reader(file)
        header = next(reader)
        comments = []
        for row in reader:
            id = row[0]
            comment = next((b for b in comments if b.id == id), None)
            if not comment:
                comment = Comment(
                    id=row[0],
                    review=Review.objects.get(id=row[1]),
                    text=row[2],
                    author=User.objects.get(id=row[3]),
                    pub_date=row[4]
                )
                comments.append(comment)
    Comment.objects.bulk_create(comments)


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('users', '0002_auto_20220821_1932'),
    ]

    operations = [
        migrations.RunPython(reviews_data)
    ]
